package it.spaghetticode.bgm.webapp.entity

import jakarta.persistence.*
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

@Entity(name = "User")
@Table(name = "USER")
data class User @JvmOverloads constructor(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long = 0,

    @Column(unique = true)
    @NotNull(message = "The username can't be null")
    @NotBlank(message = "The username can't be blank")
    @Size(min = 6, max = 80, message = "The username must be 6-80 longer")
    var username: String = "",

    @NotNull
    @NotBlank
//no validation because it's hash generated by server
    var password: String = ""
) {
    @OneToMany(
        mappedBy = "admin",
        fetch = FetchType.LAZY
    )
    var games: List<Game> = listOf()
}