DROP DATABASE IF EXISTS BoardgameMaker;
CREATE DATABASE BoardgameMaker CHAR SET UTF8 COLLATE utf8_general_ci;

USE BoardgameMaker;

CREATE TABLE USER
(
    id       BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(80)     NOT NULL,
    password VARCHAR(300)    NOT NULL
);

CREATE TABLE GAME
(
    id          BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    gameData    LONGBLOB        NOT NULL,
    name        VARCHAR(50)     NOT NULL,
    description TEXT            NOT NULL,
    likes       INT             NOT NULL    DEFAULT 0,
    idUserAdmin BIGINT UNSIGNED NOT NULL
);

CREATE TABLE LIKE_USER_GAME(
    idUser      BIGINT UNSIGNED NOT NULL,
    idGame      BIGINT UNSIGNED NOT NULL
);

ALTER TABLE USER
    ADD CONSTRAINT UK_USER_1_USERNAME
        UNIQUE (username);

ALTER TABLE GAME
    ADD CONSTRAINT FK_GAME_1_USER
        FOREIGN KEY (idUserAdmin)
            REFERENCES USER (id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;

ALTER TABLE LIKE_USER_GAME
    ADD CONSTRAINT PK
        PRIMARY KEY (idUser, idGame),
    ADD CONSTRAINT FK_LUG_1_USER
        FOREIGN KEY (idUser)
            REFERENCES USER (id)
            ON DELETE CASCADE
            ON UPDATE CASCADE,
    ADD CONSTRAINT FL_LUG_2_GAME
        FOREIGN KEY (idUser)
            REFERENCES GAME (id)
            ON DELETE CASCADE
            ON UPDATE CASCADE;

-- MASTER USER FOR THE DB
DROP USER IF EXISTS BoardgameMaker_Master;
CREATE USER BoardgameMaker_Master
    IDENTIFIED BY "bgm_m";
GRANT ALL ON BoardgameMaker.* TO BoardgameMaker_Master;

-- USER FOR WEBSITE ACTING
DROP USER IF EXISTS BoardgameMaker_Web;
CREATE USER BoardgameMaker_Web
    IDENTIFIED BY "bgm_w";
GRANT SHOW VIEW ON BoardgameMaker.* TO BoardgameMaker_Web;
GRANT ALL ON BoardgameMaker.USER TO BoardgameMaker_Web;
GRANT ALL ON BoardgameMaker.GAME TO BoardgameMaker_Web;

-- Utils
CREATE TABLE IF NOT EXISTS SPRING_SESSION (
                                PRIMARY_ID CHAR(36) NOT NULL,
                                SESSION_ID CHAR(36) NOT NULL,
                                CREATION_TIME BIGINT NOT NULL,
                                LAST_ACCESS_TIME BIGINT NOT NULL,
                                MAX_INACTIVE_INTERVAL INT NOT NULL,
                                EXPIRY_TIME BIGINT NOT NULL,
                                PRINCIPAL_NAME VARCHAR(100),
                                CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
                                           SESSION_PRIMARY_ID CHAR(36) NOT NULL,
                                           ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
                                           ATTRIBUTE_BYTES BLOB NOT NULL,
                                           CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
                                           CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

GRANT ALL ON BoardgameMaker.SPRING_SESSION TO BoardgameMaker_Web;
GRANT ALL ON BoardgameMaker.SPRING_SESSION_ATTRIBUTES TO BoardgameMaker_Web;