server:
  port: 9001
spring:
  application:
    name: BoardgameMaker WebSite
  datasource:
    username: BoardgameMaker_Web
    password: bgm_w
    url: jdbc:mariadb://localhost:3306/BoardgameMaker?allowPublicKeyRetrieval=true&useSSL=false
  sql:
    init:
      mode: always
      platform: mariadb
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
