server:
  port: 9001
  servlet:
    session:
      timeout: 86400
spring:
  servlet:
    multipart:
      max-file-size:
        -1
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
      store-type: jdbc
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
  application:
    name: BoardgameMaker WebSite
  datasource:
    username: BoardgameMaker_Web
    password: bgm_w
    url: jdbc:mariadb://localhost:3306/BoardgameMaker?allowPublicKeyRetrieval=true&useSSL=false
  sql:
    init:
      mode: always
      platform: mariadb
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  mvc:
    path match:
      matching-strategy: ant-path-matcher
