package it.spaghetticode.bgm.editor.windows;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import it.spaghetticode.bgm.core.Project;
import it.spaghetticode.bgm.core.ProjectException;
import it.spaghetticode.bgm.editor.*;
import it.spaghetticode.bgm.editor.dialogs.NewProjectDialog;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.Serializable;
import kotlinx.serialization.SerializationStrategy;
import kotlinx.serialization.json.Json;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusAdapter;
import java.awt.event.MouseAdapter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Locale;

public class Launcher extends JFrame {
    Launcher self;
    private JPanel panel1;
    private JButton newButton;
    private JButton openButton;
    private JButton settingsButton;
    private JList<Project> recentList;
    private JButton openRecentButton;
    private JButton removeRecentButton;

    public Launcher() throws HeadlessException {
        super();
        setContentPane(panel1);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);

        Listener l = new Listener();
        newButton.addActionListener(l);
        settingsButton.addActionListener(l);
        openButton.addActionListener(l);
        recentList.addListSelectionListener(l);
        openRecentButton.addActionListener(l);
        removeRecentButton.addActionListener(l);

        {
            DefaultListModel<Project> m = new DefaultListModel<Project>();
            recentList.setCellRenderer(new ProjectListRenderer());
            for (ProjectAndLocation p : MainKt.getRecentProjects()) {
                try {
                    m.addElement(p.getProject());
                } catch (Exception e) {
                    e.printStackTrace();
//                    MainKt.getRecentProjects().remove(p); //ConcurrentModificationException??
                }
            }
            MainKt.updateRecentFile();
            recentList.setModel(m);
        }

        self = this;
        recentList.addMouseListener(new MouseAdapter() {
        });
        recentList.addFocusListener(new FocusAdapter() {
        });
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        pack();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(6, 6, new Insets(5, 5, 5, 5), -1, -1));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, -1, 22, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Boardgame Maker");
        panel1.add(label1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        newButton = new JButton();
        newButton.setText("New Project");
        panel1.add(newButton, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        openButton = new JButton();
        openButton.setText("Open Project");
        panel1.add(openButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        settingsButton = new JButton();
        settingsButton.setText("Settings...");
        panel1.add(settingsButton, new GridConstraints(5, 4, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(2, 0, 3, 5, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        recentList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        recentList.setModel(defaultListModel1);
        recentList.setToolTipText("recent projects");
        scrollPane1.setViewportView(recentList);
        openRecentButton = new JButton();
        openRecentButton.setEnabled(false);
        openRecentButton.setText("Open");
        panel1.add(openRecentButton, new GridConstraints(2, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        removeRecentButton = new JButton();
        removeRecentButton.setEnabled(false);
        removeRecentButton.setText("Remove");
        panel1.add(removeRecentButton, new GridConstraints(3, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(4, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public void openProject(Project p, File location) {
        p.setLocation(location);
        if (p.getLocation() != null) {
            boolean warn = true;
            for (File f : p.getLocation().listFiles(bgmFileFilter.INSTANCE.toJavaFileFilter())) {
                String name = f.getName();
                name = name.substring(0, name.length() - 4);
                if (name.equals(p.getName())) {
                    warn = false;
                    break;
                }
            }
            if (warn) {
                boolean c = JOptionPane.showConfirmDialog(
                        self,
                        "Warning, the project's name doesn't match with the project file name!\n" +
                                "Do you want to continue anyway?",
                        "Warning",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE,
                        null) == 0;
                if (!c) {
                    return;
                }
            }
            ProjectAndLocation pal = new ProjectAndLocation(p, location.getAbsolutePath());
            MainKt.getRecentProjects().add(
                    pal
            );
            MainKt.updateRecentFile();

            try {
                FileWriter writer = new FileWriter(MainKt.getSETTINGS_PATH() + MainKt.getOPENED_PATH());
                writer.write(
                        Json.Default.encodeToString(ProjectAndLocation.getSerializer(), pal)
                );
                writer.close();
            } catch (IOException e) {
            }

            UiUtilsKt.switchView(self, new Editor(p));
        } else {
            JOptionPane.showMessageDialog(self, "Unable to find the specified location!");
        }
    }

    private class Listener implements ActionListener, ListSelectionListener {

        @Override
        public void actionPerformed(ActionEvent actionEvent) {
            Object source = actionEvent.getSource();
            if (source == newButton) {
                NewProjectDialog d = NewProjectDialog.showDialog();
                Project p = d.getProject();
                String location = d.getLocationPath();
                if (p == null) return;
                try {
                    if (!p.save(location)) {
                        throw new ProjectException("Unable to create project in specified location!");
                    }
                } catch (ProjectException e) {
                    JOptionPane.showMessageDialog(self, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                openProject(p, new File(location + "/" + p.getName()));
            } else if (source == openButton) {
                JFileChooser dialog = new JFileChooser();
                dialog.setDialogTitle("Open existing project...");
                dialog.setFileSelectionMode(JFileChooser.FILES_ONLY);
                dialog.setMultiSelectionEnabled(false);
                dialog.addChoosableFileFilter(bgmFileFilter.INSTANCE);
                dialog.setAcceptAllFileFilterUsed(false);
                dialog.showOpenDialog(self);
                File f = dialog.getSelectedFile();
                if (f == null) return;
                try {
                    Project p = Project.open(f);
                    openProject(p, f.getParentFile());
                } catch (FileNotFoundException e) {
                    JOptionPane.showMessageDialog(
                            self,
                            "Unable to open, project corrupted",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            } else if (source == settingsButton) {
                JOptionPane.showMessageDialog(self, "No settings available yet!");
            } else if (source == openRecentButton) {
                Project p = recentList.getSelectedValue();
                openProject(p, p.getLocation());
            } else if (source == removeRecentButton) {
                Project p = recentList.getSelectedValue();
                MainKt.getRecentProjects().remove(MainKt.getRecentProjects().stream().filter(projectAndLocation -> {
                    return projectAndLocation.getProject().equals(p);
                }).toArray()[0]);
                MainKt.updateRecentFile();
                ((DefaultListModel<Project>) (recentList.getModel())).removeElement(p);
            }
        }

        @Override
        public void valueChanged(ListSelectionEvent listSelectionEvent) {
            openRecentButton.setEnabled(true);
            removeRecentButton.setEnabled(true);
        }
    }
}
